### PR TITLE
feat: add tabs component

### PR DESCRIPTION
**Pull request by wawrzonnn**

### CODE REVIEW

**Review by NerdbordMentor — APPROVED** [review]
Thank you for providing me with the code changes and task requirements. Here is my code review:

### Code Changes
#### CSS
- The `.active` class now has a `::after` pseudo-element that adds a horizontal line under the active tab.
- The `.tabContent` class now has a `margin-top` of `200px`.

#### React Components
- A new `Tabs` component was created that accepts a `defaultOpenedId` prop and renders its children.
- A new `Tab` component was created that accepts an `id` prop and renders its children.
- A new `TabContent` component was created that accepts an `id` prop and renders its children if the `id` matches the active tab.

### Task Requirements
- The `Tabs` component was created using React Context API.
- The `Tabs` component was built using 3 sub-components: `Tabs`, `Tab`, and `TabContent`.
- The desired implementation was kept.
- Only one `TabContent` is visible, depending on the active `Tab`.
- The required props were provided.

### Feedback
Overall, the code changes look good and meet the task requirements. Here are some suggestions for improvement:

#### CSS
- The `.active::after` pseudo-element should have a `z-index` value greater than the `.tab` class to ensure it appears on top of the tab.

#### React Components
- The `TabContextValue` interface should be moved to a separate file and exported for reusability.
- The `Tabs`, `Tab`, and `TabContent` components should be moved to separate files and exported for reusability.
- The `TabContent` component should have a default value for the `id` prop to avoid errors when no matching tab is found.
- The `TabContent` component should have a default value for the `children` prop to avoid errors when no content is provided.
- The `Tab` component should have a default value for the `children` prop to avoid errors when no content is provided.
- The `Tab` component should have a `role` attribute of `"tab"` and an `aria-selected` attribute that reflects the active state of the tab.
- The `TabContent` component should have a `role` attribute of `"tabpanel"` and an `aria-labelledby` attribute that matches the `id` of the corresponding `Tab`.
- The `Tabs` component should have a `role` attribute of `"tablist"`.

I hope this feedback is helpful. Let me know if you have any questions or concerns.

**Review by NerdbordMentor — APPROVED** [review]
Thank you for providing me with the code changes and task requirements. Here is my code review:

## Code Review

### CSS Changes
- The CSS changes look good and are well-organized.

### Storybook Changes
- The Storybook changes look good and are well-organized.

### Component Changes
- The `Tabs` component looks good and is well-organized.
- The `Tab` component looks good and is well-organized.
- The `TabContent` component looks good and is well-organized.
- The use of `createContext` and `useContext` is appropriate for this use case.
- The `activeTabId` state is being managed correctly.
- The `setActiveTabId` function is being called correctly.
- The `handleTabClick` function is being called correctly.
- The `tabClasses` variable is being used correctly.
- The `TabContent` component is being rendered conditionally based on the active tab id.

### Task Requirements
- The `Tabs` component was created based on the provided design.
- The `react context` was used as required.
- The component was built using 3 sub-components as required.
- The desired implementation was kept as required.
- Only one `TabContent` is visible, depending on the active `Tab`.

### Suggestions
- It would be helpful to add some comments to the code to explain what each component and function does.

Overall, the code changes look good and meet the task requirements. Well done!

**Review by NerdbordMentor — APPROVED** [review]
Thank you for providing me with the code changes and task requirements. Here is my code review:

### Code Changes
#### CSS
- The `.active` class now has a `::after` pseudo-element that adds a horizontal line under the active tab.
- A new `.tabContent` class was added with a `margin-top` of `200px`.

#### React Components
- A new `Tabs` component was created that accepts a `defaultOpenedId` prop and renders its children.
- A new `Tab` component was created that accepts an `id` prop and renders its children.
- A new `TabContent` component was created that accepts an `id` prop and renders its children if the `id` matches the active tab.

### Task Requirements
- The `Tabs` component was created using React Context API.
- The `Tabs` component was built using 3 sub-components: `Tabs`, `Tab`, and `TabContent`.
- The desired implementation was kept.
- Only one `TabContent` is visible, depending on the active `Tab`.
- The required props were provided.

### Suggestions
- The CSS changes are good, but it would be better to use a more descriptive class name for the horizontal line under the active tab, such as `.active-line`.
- The `TabContent` component should extend the `TabProps` interface instead of using a separate type definition.
- It would be better to use a more descriptive name for the `defaultOpenedId` prop, such as `defaultActiveTabId`.
- It would be better to add some validation to ensure that the `id` prop of each `Tab` and `TabContent` component is unique.

Overall, the code changes meet the task requirements and are well-implemented. However, there are some minor suggestions that could improve the code further.

**Review by Sumick — CHANGES_REQUESTED** [review]
Code looks good! But we are missing code formatting here. Please, use Prettier on these changes. I wonder why it didn't work on precommit

**Review by Sumick — APPROVED** [review]
All good!

**Pull request merged**
